import Provenance.AggValue

/-!
# Congruence of predicate provenance under tie-block permutations

The occurrence payload of an aggregate token is produced by `Having.havingGroup`,
which sorts the group by the canonical order on the tuple part and breaks ties
on equal tuple parts by an arbitrary fixed order on the annotations. Pushing a
semiring homomorphism through the annotated database can therefore reorder the
payload – but only *within blocks of occurrences with equal tuple parts*, hence
equal aggregated-term values.

This file proves that the predicate provenance of a token is invariant under
exactly such reorderings. The invariance is genuinely limited to tie blocks:
for an order-sensitive aggregate, exchanging two occurrences of equal value
*across* an occurrence of a different value changes the predicate provenance.

* `TiePerm eqv` – permutations generated by transposing adjacent elements
  related by `eqv` (here: pairs with equal first components), the guarded
  analogue of `List.Perm`;
* `tiePerm_of_perm_of_sorted` – two lists that are permutations of each other
  and both sorted by a common key are related by `TiePerm` on key equality;
* `AggValue.predProvAux` – a recursion form of the predicate provenance, with
  accumulators for the values kept so far, the annotations discarded so far,
  and whether the world is already non-empty;
* `AggValue.predProv_eq_predProvAux` – the world-sum of `AggValue.predProv`
  equals the recursion form;
* `AggValue.predProv_congr` – the congruence: tokens with the same aggregate
  and `TiePerm`-related payloads have the same predicate provenance.
-/

/-! ## Tie-block permutations -/

/-- Permutations generated by transposing *adjacent* elements related by
`eqv`: the guarded analogue of `List.Perm`, whose `swap` constructor requires
the exchanged elements to be related. For `eqv` the equality of sort keys,
this captures exactly the reorderings a sort with an arbitrary tie-break can
introduce. -/
inductive TiePerm {α : Type} (eqv : α → α → Prop) : List α → List α → Prop
  | nil : TiePerm eqv [] []
  | cons (a : α) {l₁ l₂ : List α} : TiePerm eqv l₁ l₂ →
      TiePerm eqv (a :: l₁) (a :: l₂)
  | swap {a b : α} (h : eqv a b) {l₁ l₂ : List α} : TiePerm eqv l₁ l₂ →
      TiePerm eqv (a :: b :: l₁) (b :: a :: l₂)
  | trans {l₁ l₂ l₃ : List α} : TiePerm eqv l₁ l₂ → TiePerm eqv l₂ l₃ →
      TiePerm eqv l₁ l₃

namespace TiePerm

variable {α β : Type} {eqv : α → α → Prop}

theorem refl (eqv : α → α → Prop) : ∀ l : List α, TiePerm eqv l l
  | [] => .nil
  | a :: t => .cons a (refl eqv t)

theorem symm (hsymm : ∀ {a b : α}, eqv a b → eqv b a) :
    ∀ {l₁ l₂ : List α}, TiePerm eqv l₁ l₂ → TiePerm eqv l₂ l₁ := by
  intro l₁ l₂ h
  induction h with
  | nil => exact .nil
  | cons a _ ih => exact .cons a ih
  | swap h _ ih => exact .swap (hsymm h) ih
  | trans _ _ ih₁ ih₂ => exact .trans ih₂ ih₁

/-- A tie-block permutation is in particular a permutation. -/
theorem perm {l₁ l₂ : List α} (h : TiePerm eqv l₁ l₂) : l₁.Perm l₂ := by
  induction h with
  | nil => exact List.Perm.nil
  | cons a _ ih => exact ih.cons a
  | swap _ _ ih => exact (List.Perm.swap _ _ _).trans (ih.cons _ |>.cons _)
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- Tie-block permutations transport along maps that preserve the guard. -/
theorem map {eqv' : β → β → Prop} (g : α → β)
    (hg : ∀ {a b : α}, eqv a b → eqv' (g a) (g b)) :
    ∀ {l₁ l₂ : List α}, TiePerm eqv l₁ l₂ →
      TiePerm eqv' (l₁.map g) (l₂.map g) := by
  intro l₁ l₂ h
  induction h with
  | nil => exact .nil
  | cons a _ ih => exact .cons (g a) ih
  | swap h _ ih => exact .swap (hg h) ih
  | trans _ _ ih₁ ih₂ => exact .trans ih₁ ih₂

/-- On lists of pairs with equal first components as guard, a tie-block
permutation leaves the sequence of first components unchanged (whereas an
unrestricted permutation would only preserve it as a multiset). -/
theorem map_fst_eq {γ δ : Type} {l₁ l₂ : List (γ × δ)}
    (h : TiePerm (fun p q => p.1 = q.1) l₁ l₂) :
    l₁.map Prod.fst = l₂.map Prod.fst := by
  induction h with
  | nil => rfl
  | cons a _ ih => rw [List.map_cons, List.map_cons, ih]
  | swap h _ ih =>
      rw [List.map_cons, List.map_cons, List.map_cons, List.map_cons, ih, h]
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂

end TiePerm

/-! ## Sorted permutations are tie-block permutations -/

section Sorted

variable {α κ : Type} [DecidableEq α] [LinearOrder κ]

/-- Bubbling a minimal element of a sorted list to the front only ever
transposes adjacent elements of equal key. -/
theorem tiePerm_cons_erase (key : α → κ) :
    ∀ {l : List α} {p : α}, p ∈ l →
      l.Pairwise (fun x y => key x ≤ key y) →
      (∀ q ∈ l, key p ≤ key q) →
      TiePerm (fun x y => key x = key y) l (p :: l.erase p)
  | a :: t, p, hp, hsort, hmin => by
    by_cases hap : a = p
    · subst hap
      rw [List.erase_cons_head]
      exact TiePerm.refl _ _
    · have hpt : p ∈ t := by
        rcases List.mem_cons.mp hp with h | h
        · exact absurd h.symm hap
        · exact h
      have hsort' := List.pairwise_cons.mp hsort
      have ih := tiePerm_cons_erase key hpt hsort.of_cons
        (fun q hq => hmin q (List.mem_cons_of_mem a hq))
      have hkey : key a = key p :=
        le_antisymm (hsort'.1 p hpt) (hmin a List.mem_cons_self)
      rw [List.erase_cons_tail (by simpa using hap)]
      refine .trans (.cons a ih) (.swap ?_ (TiePerm.refl _ _))
      exact hkey

/-- Two lists that are permutations of each other and both sorted by the key
`key` differ only by a tie-block permutation on key equality: the sort order
determines everything except the arrangement inside blocks of equal keys. -/
theorem tiePerm_of_perm_of_sorted (key : α → κ) :
    ∀ {l₁ l₂ : List α}, l₁.Perm l₂ →
      l₁.Pairwise (fun x y => key x ≤ key y) →
      l₂.Pairwise (fun x y => key x ≤ key y) →
      TiePerm (fun x y => key x = key y) l₁ l₂
  | [], l₂, hperm, _, _ => by
    rw [hperm.symm.eq_nil]
    exact .nil
  | p :: t₁, l₂, hperm, hs₁, hs₂ => by
    have hp₂ : p ∈ l₂ := hperm.mem_iff.mp List.mem_cons_self
    have ht : t₁.Perm (l₂.erase p) := (List.cons_perm_iff_perm_erase.mp hperm).2
    have hmin : ∀ q ∈ l₂, key p ≤ key q := by
      intro q hq
      rcases List.mem_cons.mp (hperm.symm.subset hq) with h | h
      · exact le_of_eq (congrArg key h.symm)
      · exact (List.pairwise_cons.mp hs₁).1 q h
    have hbubble := tiePerm_cons_erase key hp₂ hs₂ hmin
    have ih := tiePerm_of_perm_of_sorted key ht hs₁.of_cons
      (hs₂.sublist (List.erase_sublist))
    exact .trans (.cons p ih) (TiePerm.symm (fun h => h.symm) hbubble)

end Sorted

/-! ## Position bookkeeping for the world split -/

section WorldSplit

variable {n : ℕ}

private def succEmb (n : ℕ) : Fin n ↪ Fin (n + 1) :=
  ⟨Fin.succ, Fin.succ_injective n⟩

private theorem filter_succ_insert (W' : Finset (Fin n)) :
    Finset.univ.filter
        (fun i : Fin n => i.succ ∈ insert (0 : Fin (n+1)) (W'.map (succEmb n)))
      = W' := by
  ext i
  simp [succEmb, Fin.succ_ne_zero]

private theorem filter_succ_map (W' : Finset (Fin n)) :
    Finset.univ.filter (fun i : Fin n => i.succ ∈ W'.map (succEmb n)) = W' := by
  ext i
  simp [succEmb]

private theorem notMem_map_succ (W' : Finset (Fin n)) :
    (0 : Fin (n+1)) ∉ W'.map (succEmb n) := by
  simp [succEmb, Fin.succ_ne_zero]

private theorem compl_map (W' : Finset (Fin n)) :
    (W'.map (succEmb n))ᶜ = insert (0 : Fin (n+1)) (W'ᶜ.map (succEmb n)) := by
  ext i
  cases i using Fin.cases with
  | zero => simp [succEmb, Fin.succ_ne_zero]
  | succ j => simp [succEmb, Fin.succ_ne_zero]

private theorem compl_insert_map (W' : Finset (Fin n)) :
    (insert (0 : Fin (n+1)) (W'.map (succEmb n)))ᶜ = W'ᶜ.map (succEmb n) := by
  rw [Finset.compl_insert, compl_map, Finset.erase_insert (notMem_map_succ _)]

private theorem insert_filter {W : Finset (Fin (n+1))} (h0 : (0 : Fin (n+1)) ∈ W) :
    insert (0 : Fin (n+1))
        ((Finset.univ.filter (fun i : Fin n => i.succ ∈ W)).map (succEmb n))
      = W := by
  ext i
  cases i using Fin.cases with
  | zero => simp [h0]
  | succ j => simp [succEmb, Fin.succ_ne_zero]

private theorem map_filter {W : Finset (Fin (n+1))} (h0 : (0 : Fin (n+1)) ∉ W) :
    (Finset.univ.filter (fun i : Fin n => i.succ ∈ W)).map (succEmb n) = W := by
  ext i
  cases i using Fin.cases with
  | zero => simp [succEmb, Fin.succ_ne_zero, h0]
  | succ j => simp [succEmb]

private def insertEmb (n : ℕ) : Finset (Fin n) ↪ Finset (Fin (n + 1)) :=
  ⟨fun W' => insert 0 (W'.map (succEmb n)),
   fun W₁ W₂ h => by
    have h' : insert (0 : Fin (n+1)) (W₁.map (succEmb n))
        = insert 0 (W₂.map (succEmb n)) := h
    rw [← filter_succ_insert W₁, h', filter_succ_insert]⟩

private def mapEmb (n : ℕ) : Finset (Fin n) ↪ Finset (Fin (n + 1)) :=
  ⟨fun W' => W'.map (succEmb n),
   fun W₁ W₂ h => by
    have h' : W₁.map (succEmb n) = W₂.map (succEmb n) := h
    rw [← filter_succ_map W₁, h', filter_succ_map]⟩

end WorldSplit

/-! ## The recursion form of predicate provenance -/

namespace AggValue

variable {T K : Type} [ValueType T] [CommSemiringWithMonus K] [DecidableEq K]

/-- Recursion form of the predicate provenance of a token: `acc` accumulates
the values of the occurrences kept so far, `ex` the sum of the annotations of
the occurrences discarded so far, and `started` records whether an occurrence
has been kept (worlds must end up non-empty). Keeping an occurrence
contributes its annotation as a factor; discarding it moves its annotation
into the pending `𝟙 ⊖ Σ` factor materialized at the end of the list. -/
def predProvAux (f : SeqAggFunc T) (op : CompOp) (c : T) :
    List T → K → Bool → List (T × K) → K
  | acc, ex, started, [] =>
      if started then (1 - ex) * Having.chi op (f acc) c else 0
  | acc, ex, started, (v, a) :: t =>
      a * predProvAux f op c (acc ++ [v]) ex true t
        + predProvAux f op c acc (ex + a) started t

omit [DecidableEq K] in
/-- The world-sum defining the predicate provenance, generalized by the three
accumulators, equals the recursion form. -/
theorem sum_worlds_eq_predProvAux (f : SeqAggFunc T) (op : CompOp) (c : T) :
    ∀ (l : List (T × K)) (acc : List T) (ex : K) (started : Bool),
      ∑ W ∈ Finset.univ.filter
          (fun W : Finset (Fin l.length) => started = true ∨ W.Nonempty),
        (∏ i ∈ W, (l.get i).snd)
          * ((1 - (ex + ∑ i ∈ Wᶜ, (l.get i).snd))
            * Having.chi op (f (acc ++ (Having.seqOf l W).map Prod.fst)) c)
        = predProvAux f op c acc ex started l
  | [], acc, ex, started => by
    have hW : ∀ W : Finset (Fin ([] : List (T × K)).length), W = ∅ := fun W =>
      Finset.eq_empty_of_forall_notMem (fun i => absurd i.isLt (Nat.not_lt_zero _))
    cases started with
    | false =>
        rw [Finset.filter_false_of_mem, Finset.sum_empty]
        · rfl
        · intro W _
          rw [hW W]
          simp
    | true =>
        rw [Finset.filter_true_of_mem (fun _ _ => Or.inl rfl)]
        rw [show (Finset.univ : Finset (Finset (Fin ([] : List (T × K)).length)))
            = {∅} from Finset.eq_singleton_iff_unique_mem.mpr
              ⟨Finset.mem_univ _, fun W _ => hW W⟩]
        rw [Finset.sum_singleton, Finset.prod_empty, one_mul,
          Finset.sum_eq_zero (fun i _ => absurd i.isLt (Nat.not_lt_zero _)),
          add_zero]
        show (1 - ex) * Having.chi op (f (acc ++ [])) c = _
        rw [List.append_nil]
        rfl
  | (v, ann) :: t, acc, ex, started => by
    have ih := sum_worlds_eq_predProvAux f op c t
    dsimp only [List.length_cons]
    -- Branch A: worlds keeping the head occurrence.
    have hA : (∑ W ∈ (Finset.univ.filter
          (fun W : Finset (Fin (t.length + 1)) => started = true ∨ W.Nonempty)).filter
            (fun W => (0 : Fin (t.length + 1)) ∈ W),
          (∏ i ∈ W, (((v, ann) :: t).get i).snd)
            * ((1 - (ex + ∑ i ∈ Wᶜ, (((v, ann) :: t).get i).snd))
              * Having.chi op
                  (f (acc ++ (Having.seqOf ((v, ann) :: t) W).map Prod.fst)) c))
        = ann * predProvAux f op c (acc ++ [v]) ex true t := by
      rw [Finset.filter_filter]
      rw [show Finset.univ.filter
            (fun W : Finset (Fin (t.length + 1)) =>
              (started = true ∨ W.Nonempty) ∧ (0 : Fin (t.length + 1)) ∈ W)
          = (Finset.univ : Finset (Finset (Fin t.length))).map (insertEmb t.length)
          from by
        ext W
        constructor
        · intro hW
          have h0 : (0 : Fin (t.length + 1)) ∈ W := (Finset.mem_filter.mp hW).2.2
          exact Finset.mem_map.mpr ⟨Finset.univ.filter (fun i => i.succ ∈ W),
            Finset.mem_univ _, insert_filter h0⟩
        · intro hW
          obtain ⟨W', -, rfl⟩ := Finset.mem_map.mp hW
          have h0 : (0 : Fin (t.length + 1)) ∈ insertEmb t.length W' :=
            Finset.mem_insert_self _ _
          exact Finset.mem_filter.mpr ⟨Finset.mem_univ _, Or.inr ⟨0, h0⟩, h0⟩]
      rw [Finset.sum_map, ← ih (acc ++ [v]) ex true,
        Finset.filter_true_of_mem (fun _ _ => Or.inl rfl), Finset.mul_sum]
      refine Finset.sum_congr rfl fun W' _ => ?_
      have hprod : ∏ i ∈ insertEmb t.length W', (((v, ann) :: t).get i).snd
          = ann * ∏ i ∈ W', (t.get i).snd := by
        show ∏ i ∈ insert (0 : Fin (t.length + 1)) (W'.map (succEmb t.length)),
            (((v, ann) :: t).get i).snd = _
        rw [Finset.prod_insert (notMem_map_succ _), Finset.prod_map]
        exact congrArg₂ (· * ·) rfl (Finset.prod_congr rfl fun i _ => rfl)
      have hsum : ∑ i ∈ (insertEmb t.length W')ᶜ, (((v, ann) :: t).get i).snd
          = ∑ i ∈ W'ᶜ, (t.get i).snd := by
        show ∑ i ∈ (insert (0 : Fin (t.length + 1))
            (W'.map (succEmb t.length)))ᶜ, (((v, ann) :: t).get i).snd = _
        rw [compl_insert_map, Finset.sum_map]
        exact Finset.sum_congr rfl fun i _ => rfl
      have hseq : Having.seqOf ((v, ann) :: t) (insertEmb t.length W')
          = (v, ann) :: Having.seqOf t W' := by
        show Having.seqOf ((v, ann) :: t)
            (insert (0 : Fin (t.length + 1)) (W'.map (succEmb t.length))) = _
        simp only [Having.seqOf]
        rw [if_pos (Finset.mem_insert_self _ _), filter_succ_insert]
        rfl
      rw [hprod, hsum, hseq, List.map_cons]
      dsimp only
      rw [List.append_cons acc v ((Having.seqOf t W').map Prod.fst), mul_assoc]
    -- Branch B: worlds discarding the head occurrence.
    have hB : (∑ W ∈ (Finset.univ.filter
          (fun W : Finset (Fin (t.length + 1)) => started = true ∨ W.Nonempty)).filter
            (fun W => ¬ (0 : Fin (t.length + 1)) ∈ W),
          (∏ i ∈ W, (((v, ann) :: t).get i).snd)
            * ((1 - (ex + ∑ i ∈ Wᶜ, (((v, ann) :: t).get i).snd))
              * Having.chi op
                  (f (acc ++ (Having.seqOf ((v, ann) :: t) W).map Prod.fst)) c))
        = predProvAux f op c acc (ex + ann) started t := by
      rw [Finset.filter_filter]
      rw [show Finset.univ.filter
            (fun W : Finset (Fin (t.length + 1)) =>
              (started = true ∨ W.Nonempty) ∧ ¬ (0 : Fin (t.length + 1)) ∈ W)
          = (Finset.univ.filter
              (fun W' : Finset (Fin t.length) => started = true ∨ W'.Nonempty)).map
              (mapEmb t.length)
          from by
        ext W
        constructor
        · intro hW
          obtain ⟨-, hP, h0⟩ := Finset.mem_filter.mp hW
          refine Finset.mem_map.mpr ⟨Finset.univ.filter (fun i => i.succ ∈ W),
            Finset.mem_filter.mpr ⟨Finset.mem_univ _, ?_⟩, map_filter h0⟩
          rcases hP with hs | ⟨i, hi⟩
          · exact Or.inl hs
          · refine Or.inr ?_
            cases i using Fin.cases with
            | zero => exact absurd hi h0
            | succ j =>
                exact ⟨j, Finset.mem_filter.mpr ⟨Finset.mem_univ _, hi⟩⟩
        · intro hW
          obtain ⟨W', hW', rfl⟩ := Finset.mem_map.mp hW
          refine Finset.mem_filter.mpr
            ⟨Finset.mem_univ _, ?_, notMem_map_succ W'⟩
          rcases (Finset.mem_filter.mp hW').2 with hs | ⟨j, hj⟩
          · exact Or.inl hs
          · exact Or.inr ⟨succEmb t.length j, Finset.mem_map_of_mem _ hj⟩]
      rw [Finset.sum_map, ← ih acc (ex + ann) started]
      refine Finset.sum_congr rfl fun W' _ => ?_
      have hprod : ∏ i ∈ mapEmb t.length W', (((v, ann) :: t).get i).snd
          = ∏ i ∈ W', (t.get i).snd := by
        show ∏ i ∈ W'.map (succEmb t.length), (((v, ann) :: t).get i).snd = _
        rw [Finset.prod_map]
        exact Finset.prod_congr rfl fun i _ => rfl
      have hsum : ∑ i ∈ (mapEmb t.length W')ᶜ, (((v, ann) :: t).get i).snd
          = ann + ∑ i ∈ W'ᶜ, (t.get i).snd := by
        show ∑ i ∈ (W'.map (succEmb t.length))ᶜ, (((v, ann) :: t).get i).snd = _
        rw [compl_map, Finset.sum_insert (notMem_map_succ _), Finset.sum_map]
        exact congrArg₂ (· + ·) rfl (Finset.sum_congr rfl fun i _ => rfl)
      have hseq : Having.seqOf ((v, ann) :: t) (mapEmb t.length W')
          = Having.seqOf t W' := by
        show Having.seqOf ((v, ann) :: t) (W'.map (succEmb t.length)) = _
        simp only [Having.seqOf]
        rw [if_neg (notMem_map_succ _), filter_succ_map]
        rfl
      rw [hprod, hsum, hseq, ← add_assoc]
    rw [← Finset.sum_filter_add_sum_filter_not
      (Finset.univ.filter
        (fun W : Finset (Fin (t.length + 1)) => started = true ∨ W.Nonempty))
      (fun W => (0 : Fin (t.length + 1)) ∈ W)]
    rw [hA, hB]
    simp only [predProvAux]

/-- The predicate provenance of a token is its recursion form. -/
theorem predProv_eq_predProvAux (a : AggValue T K) (op : CompOp) (c : T) :
    a.predProv op c = predProvAux a.agg op c [] 0 false a.occs := by
  rw [← sum_worlds_eq_predProvAux]
  simp only [AggValue.predProv]
  refine Finset.sum_congr (Finset.filter_congr fun W _ => by simp) fun W _ => ?_
  simp only [Having.worldAnn, AggValue.anns, AggValue.valOn]
  rw [zero_add, List.nil_append, mul_assoc]

omit [DecidableEq K] in
/-- The recursion form is invariant under tie-block permutations of the
payload: exchanging two adjacent occurrences with equal values redistributes
the same annotations over the same world readings. -/
theorem predProvAux_congr (f : SeqAggFunc T) (op : CompOp) (c : T)
    {l₁ l₂ : List (T × K)} (h : TiePerm (fun p q => p.1 = q.1) l₁ l₂) :
    ∀ (acc : List T) (ex : K) (started : Bool),
      predProvAux f op c acc ex started l₁
        = predProvAux f op c acc ex started l₂ := by
  induction h with
  | nil => intro acc ex started; rfl
  | @cons p l₁ l₂ _ ih =>
      intro acc ex started
      obtain ⟨v, a⟩ := p
      simp only [predProvAux]
      rw [ih, ih]
  | @swap p q hpq l₁ l₂ _ ih =>
      intro acc ex started
      obtain ⟨v, a⟩ := p
      obtain ⟨w, b⟩ := q
      dsimp only at hpq
      subst hpq
      simp only [predProvAux]
      simp only [ih]
      simp only [mul_add]
      rw [mul_left_comm a b, add_right_comm ex a b]
      exact add_add_add_comm _ _ _ _
  | trans _ _ ih₁ ih₂ =>
      intro acc ex started
      rw [ih₁, ih₂]

/-- **Congruence of predicate provenance**: tokens with the same aggregate
whose payloads differ by a tie-block permutation on equal values have the
same predicate provenance, for every comparison. This is what makes the
annotation tie-break of the group sort semantically invisible. -/
theorem predProv_congr {a b : AggValue T K} (hagg : a.agg = b.agg)
    (h : TiePerm (fun p q => p.1 = q.1) a.occs b.occs)
    (op : CompOp) (c : T) :
    a.predProv op c = b.predProv op c := by
  rw [predProv_eq_predProvAux, predProv_eq_predProvAux, hagg,
    predProvAux_congr b.agg op c h]

omit [ValueType T] [CommSemiringWithMonus K] [DecidableEq K] in
/-- The deterministic reading of a token only depends on the value sequence,
which a tie-block permutation preserves. -/
theorem collapse_congr {a b : AggValue T K} (hagg : a.agg = b.agg)
    (h : TiePerm (fun p q => p.1 = q.1) a.occs b.occs) :
    a.collapse = b.collapse := by
  rw [AggValue.collapse, AggValue.collapse, hagg, h.map_fst_eq]

omit [ValueType T] [DecidableEq K] in
/-- The sum of the occurrence annotations of a token is invariant under any
permutation of the payload, in particular a tie-block one. -/
theorem annSum_congr {a b : AggValue T K}
    (h : TiePerm (fun p q => p.1 = q.1) a.occs b.occs) :
    (a.occs.map Prod.snd).sum = (b.occs.map Prod.snd).sum :=
  (h.perm.map Prod.snd).sum_eq

end AggValue
