/-
  Released under the MIT license as described in the file LICENSE.
  Authors: Pierre Senellart
-/
import Mathlib.Algebra.BigOperators.Group.Multiset.Basic
import Mathlib.Data.Multiset.Sort
import Provenance.SemiringWithMonus

/-!
# K-semimodules and the free K-tensor

This file develops the algebraic infrastructure required to interpret the
aggregation operator on `K`-annotated relations, following the framework of
[Amsterdamer, Deutch & Tannen, *Provenance for aggregate queries*][amsterdamer2011aggregate]
(Section IV-B, Definition 7 of [Sen, Maniu & Senellart, *ProvSQL*][sen2026provsql]).

## Main definitions

* `KSemiModule K M` — a left action of a `CommSemiringWithMonus K` on an
  `AddCommMonoid M` satisfying the six standard semimodule axioms
  (`zero_smul`, `one_smul`, `add_smul`, `smul_add`, `smul_zero`,
  `mul_smul`). The same axioms as Mathlib's `Module`, exposed under our
  own name so that downstream provenance proofs depend on
  `CommSemiringWithMonus` directly (not on the more abstract `Semiring`).

* `KTensor K M` — a representation of the free formal sums `∑ αᵢ ⊗ mᵢ`,
  realised as a `Multiset (K × M)` of monomials. Has `Zero`, `Add` and
  `AddCommMonoid`, plus a scalar action `KTensor.smul`, an `embed` map
  `(K × M) → KTensor K M`, and a contraction `bind` operator.

  Note: `KTensor K M` is **not** claimed to be a `KSemiModule K`. The
  underlying `Multiset (K × M)` is the free formal sum modulo permutation
  only; bilinearity relations such as `(α + β) ⊗ m = α ⊗ m + β ⊗ m`,
  `0 ⊗ m = 0`, and `α ⊗ (m₁ + m₂) = α ⊗ m₁ + α ⊗ m₂` are *not* enforced.
  Quotienting by those relations gives Mathlib-style `TensorProduct`,
  which is the right target for correctness theorems but adds substantial
  setoid-quotient machinery; the un-quotiented representation is enough
  for evaluating aggregations end-to-end.

## Main results

* `instance : KSemiModule K K` — the canonical action of a
  `CommSemiringWithMonus K` on itself via multiplication.

## References

* [Amsterdamer, Deutch & Tannen][amsterdamer2011aggregate]
* [Sen, Maniu & Senellart][sen2026provsql] (Section IV-B, Def. 7)
-/

/-! ## The `KSemiModule` typeclass -/

/-- A `K`-semimodule structure on an additive commutative monoid `M`,
relative to a `CommSemiringWithMonus K`. The six axioms are the
bilinearity of the action `(α, m) ↦ α • m`, matching Mathlib's `Module`
over a semiring. -/
class KSemiModule (K : Type) (M : Type) [CommSemiringWithMonus K]
    [AddCommMonoid M] where
  /-- Left action of `K` on `M`. -/
  smul : K → M → M
  /-- `0 • m = 0`: the zero of `K` annihilates `m`. -/
  zero_smul : ∀ m : M, smul 0 m = 0
  /-- `1 • m = m`: the multiplicative unit of `K` acts trivially. -/
  one_smul : ∀ m : M, smul 1 m = m
  /-- `(α + β) • m = α • m + β • m`: distributivity over `K`'s addition. -/
  add_smul : ∀ α β : K, ∀ m : M, smul (α + β) m = smul α m + smul β m
  /-- `α • (m + n) = α • m + α • n`: distributivity over `M`'s addition. -/
  smul_add : ∀ α : K, ∀ m n : M, smul α (m + n) = smul α m + smul α n
  /-- `α • 0 = 0`: the action sends `0 : M` to `0`. -/
  smul_zero : ∀ α : K, smul α 0 = 0
  /-- `(α * β) • m = α • (β • m)`: the action is multiplicative in `K`. -/
  mul_smul : ∀ α β : K, ∀ m : M, smul (α * β) m = smul α (smul β m)

namespace KSemiModule

/-- Infix notation for the `KSemiModule` action. We deliberately do not use
Mathlib's `•` to avoid forcing instance resolution on every
`SemiringWithMonus`-flavoured proof. -/
scoped infixr:73 " ⋆ₖ " => KSemiModule.smul

end KSemiModule

/-! ### Canonical instance: every `CommSemiringWithMonus` acts on itself. -/

/-- The canonical `K`-semimodule structure on `K` itself: the action is the
semiring's multiplication. -/
instance CommSemiringWithMonus.instKSemiModuleSelf
    {K : Type} [CommSemiringWithMonus K] : KSemiModule K K where
  smul := (· * ·)
  zero_smul := zero_mul
  one_smul := one_mul
  add_smul a b m := by rw [add_mul]
  smul_add a m n := by rw [mul_add]
  smul_zero := mul_zero
  mul_smul a b m := by rw [mul_assoc]

/-! ## The free `K`-tensor `KTensor K M`

A formal-sum representation of the free `K`-module generated by `M`.
Each element is a multiset of monomials `(α, m) : K × M`. Addition is
multiset union; the scalar action `(β, t) ↦ β • t` multiplies the
`K`-coefficient of each monomial by `β` on the left.

The representation is the **free** formal sum modulo permutation only:
bilinearity relations like `(α₁ + α₂) ⊗ m = α₁ ⊗ m + α₂ ⊗ m` are *not*
enforced. Equality in the un-quotiented `KTensor K M` is stricter than
in the proper tensor product `K ⊗ M`. We expose this data structure
because it is enough to *evaluate* aggregations; the proper quotient
will appear once we state and prove correctness theorems for the
aggregation semantics.
-/

/-- The free `K`-tensor on a type `M`: a formal sum of `K`-weighted
elements of `M`. -/
def KTensor (K : Type) (M : Type) : Type := Multiset (K × M)

namespace KTensor

variable {K : Type} {M : Type}

instance : Zero (KTensor K M) :=
  inferInstanceAs (Zero (Multiset (K × M)))

instance : Add (KTensor K M) :=
  inferInstanceAs (Add (Multiset (K × M)))

instance : AddCommMonoid (KTensor K M) :=
  inferInstanceAs (AddCommMonoid (Multiset (K × M)))

-- Mathlib's `Repr (Multiset α)` is `unsafe`, so the propagated instance for
-- `KTensor K M` is too. `#eval!` accepts unsafe instances.
unsafe instance [Repr K] [Repr M] : Repr (KTensor K M) :=
  inferInstanceAs (Repr (Multiset (K × M)))

/-- Embed a single monomial `(α, m)` as the formal sum `α ⊗ m`. -/
def embed (α : K) (m : M) : KTensor K M := ({(α, m)} : Multiset (K × M))

/-- Push a `KTensor K M` forward along a function `f : K → K'`, mapping each
monomial's K-coefficient through `f`. Used in particular to push forward
along a `SemiringWithMonusHom`. -/
def mapHom {K' : Type} (f : K → K') (t : KTensor K M) : KTensor K' M :=
  (t : Multiset (K × M)).map (fun p => (f p.fst, p.snd))

@[simp] theorem mapHom_zero {K' : Type} (f : K → K') :
    mapHom (M := M) f 0 = 0 := by
  show (0 : Multiset (K × M)).map _ = 0
  rw [Multiset.map_zero]

@[simp] theorem mapHom_add {K' : Type} (f : K → K') (t u : KTensor K M) :
    mapHom f (t + u) = mapHom f t + mapHom f u :=
  Multiset.map_add (fun p : K × M => (f p.fst, p.snd)) t u

@[simp] theorem mapHom_embed {K' : Type} (f : K → K') (α : K) (m : M) :
    mapHom f (embed α m) = embed (f α) m := rfl

variable [CommSemiringWithMonus K]

/-- Scalar action of `K` on `KTensor K M`: multiply the `K`-coefficient of
each monomial by `β` on the left. This is **not** the action of a
`KSemiModule` instance, because the un-quotiented representation does
not satisfy `add_smul` or `zero_smul`; we expose it as a plain function
for use in the aggregation evaluator. -/
def smul (β : K) (t : KTensor K M) : KTensor K M :=
  (t : Multiset (K × M)).map (fun p => (β * p.fst, p.snd))

@[simp] theorem smul_zero (β : K) : smul β (0 : KTensor K M) = 0 := by
  show (0 : Multiset (K × M)).map _ = 0
  rw [Multiset.map_zero]

@[simp] theorem smul_add (β : K) (t u : KTensor K M) :
    smul β (t + u) = smul β t + smul β u :=
  Multiset.map_add (fun p : K × M => (β * p.fst, p.snd)) t u

@[simp] theorem one_smul (t : KTensor K M) : smul 1 t = t := by
  show (t : Multiset (K × M)).map (fun p => (1 * p.fst, p.snd)) = t
  have h : (fun p : K × M => (1 * p.fst, p.snd)) = id := by
    funext p; rcases p with ⟨a, b⟩; simp
  rw [h, Multiset.map_id]

theorem smul_embed (β α : K) (m : M) : smul β (embed α m) = embed (β * α) m :=
  rfl

end KTensor
